### ISSUE TITLE
Install script: Issues with screen & audio

### ISSUE THREAD

**Issue by vyruz1986** [kiteretro/Circuit-Sword-Lite#7]
Thanks for this awesome hardware, I'm really happy with it 👍 

So the image works perfectly on my build, I have  a working screen and audio with some test roms I put on the SD card.
However, I'd like to use one of the prebuild images floating around the net, so I loaded such an image, enabled wifi through `/boot/wpa_supplicant.conf` and ssh through putting an empty `/boot/ssh` file on the sd card. I could then access my build over SSH. 

then I followed the instructions on this repo, cloned the repo and ran `sudo ./install.sh YES` This performed all necessary actions without errors, and after rebooting my screen came up with K boot logo and I could navigate through the Retropie menus, seeing all the roms I had on the image etc. The Wifi and battery icon show up fine as well.

However, when I try to start a game, or even go into one of the Retropie screens (like 'Show IP' for example), the screen goes black with just the Wifi and battery icon remaining visible.

As I'm struggling with this screen issue, I can't test audio in-game, but on this image I'm using the there's an MP3 playing in the menu, which can not be heard after running your install script, so it seems the Audio is not being configured correctly either.

Any suggestions that I could try? Thanks for your help!

**Comment by kiteretro** [comment]
Hi!

The black screens when entering menus, i'm not sure of what that is about.. the thing that is meant to appear is a curses style menu thing.. what you might want to try is exiting ES, and then via SSH run `emulationstation` as a command.. and then on the screen do the menu.. the ssh console MIGHT show you some more information (hopefully some error messages or something) .. otherwise looking up where the ES log file is (i don't know if/where it exists at the mo).

You will not be able to get audio working in ES main menu thing, that's expected, because the CSL uses USB audio and you have to rebuild ES to work with that which no one does.. if you try launching something or from the command line playing an mp3 or something MIGHT work? Launching apps should have sound though.. 

See where you get with that

**Comment by vyruz1986** [comment]
So apparently the audio issue was the cause of the screen going black as well. On [this topic](https://sudomod.com/forum/viewtopic.php?t=3950) I read that a missing sound card could result in emulationstation not starting correctly. So I started checking and eventually found out I had a bad solder joint in the USB cable going from the Pi zero to the CSL. I fixed it and now everything works like a charm.
